// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOR8X_YvZtsbt1T8hRFuOEbxqoNCq2D0',
    appId: '1:855274696249:web:ba6c6bd8e9aa42d69367e8',
    messagingSenderId: '855274696249',
    projectId: 'task-ebbb7',
    authDomain: 'task-ebbb7.firebaseapp.com',
    storageBucket: 'task-ebbb7.firebasestorage.app',
    measurementId: 'G-SH6JNPXKB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjt3NNQyqaTfPH9ShGk7s93gRIzjdqAA4',
    appId: '1:855274696249:android:d73ca993663088ff9367e8',
    messagingSenderId: '855274696249',
    projectId: 'task-ebbb7',
    storageBucket: 'task-ebbb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIr7-F09wbdbQVjBDC9TXj6YCgs3WbmYo',
    appId: '1:855274696249:ios:c2d96dc2666e5b5b9367e8',
    messagingSenderId: '855274696249',
    projectId: 'task-ebbb7',
    storageBucket: 'task-ebbb7.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIr7-F09wbdbQVjBDC9TXj6YCgs3WbmYo',
    appId: '1:855274696249:ios:c2d96dc2666e5b5b9367e8',
    messagingSenderId: '855274696249',
    projectId: 'task-ebbb7',
    storageBucket: 'task-ebbb7.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGOR8X_YvZtsbt1T8hRFuOEbxqoNCq2D0',
    appId: '1:855274696249:web:8581cf5f3e00580a9367e8',
    messagingSenderId: '855274696249',
    projectId: 'task-ebbb7',
    authDomain: 'task-ebbb7.firebaseapp.com',
    storageBucket: 'task-ebbb7.firebasestorage.app',
    measurementId: 'G-LF0HW9KHXV',
  );
}
